### ISSUE TITLE
unable to download amazon.csv

### ISSUE THREAD

**Issue by bzankay** [daroczig/CEU-R-lab#14]
Dear Gergely,
I have stored the amazon,csv file on my computer as: C:\Windows\System32\config\systemprofile\AppData\Roaming\Microsoft\Windows\Recent      
When trying to download to R I have this reply :
> read.csv(C:\Windows\System32\config\systemprofile\AppData\Roaming\Microsoft\Windows\Recent)
Error: unexpected input in "read.csv(C:\"
I have tried to change \ to /   but it did not help. I also tried to add: \amazon.csv) to the end of the line. Then tried to fill with help function: read.csv(file, header = TRUE, sep = ",", quote = "\"",
         dec = ".", fill = TRUE, comment.char = "", ...) but it was not working either (it is possible that I did not use it properly...)
Do you have any hint at what I'm doing wrong?

**Comment by bzankay** [comment]
I saved the excel file again in a different place on C:\\Users\\Balázs user
then I tried this:
  > read.csv('C:\\Users\\Balázs user')

resulted:

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'C:\Users\Balázs user': Permission denied

I'm sorry to bother you with this, but I have no access to any other help right now

**Comment by bzankay** [comment]
solved ...:-)

**Comment by daroczig** [comment]
I think the issue with the first using the `/` separator was that you missed the quotes around the file path/name. For the separator, you should either use `/` or if you want to stick with the Windows-style `\`, then you have to escape it, basically double it to `\\`. In the second error message, I think you tried to read a folder instead of a file. I'm glad you managed to solve it after all :)
