### ISSUE TITLE
Problems with ggplot 

### ISSUE THREAD

**Issue by bzankay** [daroczig/CEU-R-lab#18]
Hi Gergo,

unfortunately I have some difficulties with applying ggplot. On the first slide of the assignment I tried this:

install.packages(‘ggplot2’)
library(ggplot2)
str(diamonds)
install.packages(‘data.table’)
dt <- data.table(diamonds)

,then I have this in the console:

Parsing error in script.R:1:18: unexpected '<'
1: install.packages(<
                     ^

Is it something I'm doing wrong, or might be some set up problem?  Anyhow, it seems I'm able to use ggplot functions throughout the session though...

An other issue, I would like ask for your opinion: whenever I'm trying to submit answer in Datacamp, the connection with server is often down, i.e. the spot in the upper right corner changes from green to yellow when I click on "submit answer", obviously restraining completion. Do you think Datacamp's server is to be blamed, or my lap top may have some connectivity problem?

Thanks in advance,

BR

Balazs Zankay

**Comment by daroczig** [comment]
Hey,

I think there's a strange char in the first line instead of  a single quote -- maybe that's causing the problem?

Anyway, you don't need to `install.packages` on DataCamp, these packages are already installed, so juts load via `library`. I hope that helps.

Unfortunately, others also reported tech issues with the DataCamp servers, so I guess that's an issue on their end. Sorry for the inconvenience :/

Please let me know if we can close this ticket or if there's anything else I could try to help with.

**Comment by bzankay** [comment]
I'm fine, thank you!
