### ISSUE TITLE
A More Complex Summary

### ISSUE THREAD

**Issue by kgbgergo** [daroczig/CEU-R-lab#23]
Hi Gergely

I've encountered the below error message, stating that I used "na.rm" in the function. However there's no na.rm written in my code:
![image](https://user-images.githubusercontent.com/32012042/31725228-1fbb44ec-b424-11e7-8c2e-cf2cc5689dcd.png)

What did I do wrong? 
Thank you!

Kinizsi Gergely

**Comment by daroczig** [comment]
`min(air_time, na.rm = TRUE)` is coming from the solution ... So when you submit your answer, DataCamp will evaluate that and the solution as well, then it compares the results.

I think as you defined a `min` variable, somehow it's conflicting with the `min` function. This seems to be a bug FTR in DataCamp, but instead of further debugging, I'm suggesting to try to solve this exercise in a much simpler way: do the aggregate in one command something like:

```
dt[, list(
  col1 = foo(air_time),
  col2 = bar(air_time)), by = foobar)]
```
