### ISSUE TITLE
New computer

### ISSUE THREAD

**Issue by shotsubakiyama** [daroczig/CEU-R-lab#32]
Quick question regarding a new laptop purchase. Given your background and experience, do you have any recommendations for laptop purchases for beginner data scientists? Perhaps a couple under $800 and a couple over? I'm sure it depends a lot depending on what you're trying to do with it, but do you have any general recommendations for people starting out in data science but looking to get more immersed like ourselves?

Many thanks in advance!

**Comment by daroczig** [comment]
Depending on your operating system preferences, there are a bunch of options. I prefer Linux so that I can customize my work environment to my exact needs, and Lenovo T series usually provides a good support on it. If you are on Windows, probably any vendor should be fine. And there are many folks using Macs, as being still based on UNIX and giving easy access to UNIX-based tools, yet providing a user-friendly interface on the top of that.

Regarding HW: I'd suggest a dual core machine with at least 4, preferably 8 gigs of RAM. Avoid Celeron and such low performance processors. And make sure to get an SSD instead of a traditional HDD, as SSDs are much faster and less prone to error in mobile devices. Regarding screen: it's again up to what you prefer, there are many folks using glossy screens with bright colors, while I prefer matte display without any screen reflection issues. Same on resolution: many folks are OK with low resolution, I prefer 1920x1080 even on 14" with small font size so that I can see a lot of source code even on one screen :)

I hope this helped a bit, although I cannot really suggest a specific model or type. One hint though: make sore to also look at used (1-3 yrs old) but very durable and professional business laptops instead of cheap consumer machines.
