### ISSUE TITLE
Thesis Project Idea Recommendations: Key Learning Outcomes

### ISSUE THREAD

**Issue by shotsubakiyama** [daroczig/CEU-R-lab#34]
Thank you for your suggestions regarding laptop specs! I will definitely keep them in mind.

One more question. Regarding our final thesis. Do you have any recommendations regarding what topics we should focus on / practice in our thesis projects?

As an experienced data scientist, what would you say are some key skills that are sought in the market, crucial to job searches, and strong value adds for our current and future companies? From my perspective, I would like to make the most of this thesis experience and learn as many of the "must know" skills that an entry level data scientist should have experience in.  Especially in terms of R, what are some key exercises that we can learn and develop during this exercise?

Many thanks for your help!

**Comment by daroczig** [comment]
Some random, although hopefully useful thoughts on these:

- on the job market, you make the first impressions with your presentation skills, so I'd suggest spending some time on that :) that means not only how to create a slide show, but how you introduce yourself, what materials you make available on your background (eg Github, stackoverflow or datacamp profile), and eg how you approach and discuss business questions
- even at a later point, I think presentation skills count quite a lot and even a pretty basic DS project can be much more successful if well presented compared to a solution using sophisticated and cutting-edge methodology without proper interpretation and exec summary
- as you are currently building your DS profile, I'd do all the future projects publicly in the open space so that others can see that later. or feel free to work in private mode, but make sure to publish your data, analysis and results later -- eg on Github
- pick a project idea where you can find open data, and hopefully a community around it. that way you'll be able to make sure that you create a reproducible workflow (probably published on GH), ask around in the community, do some networking, get help from more experienced folks there and give back with the results of the analysis
- regarding most important technical skills you might need as a junior data scientist: presentations sw, sql, git/github, r or python or a graphical BI tool

As I have no explicit pointers, I'm closing this ticket, but please feel free to reopen with specific questions
